// Types
import type { GrammarCategory } from '@/types/grammarTopic'

export const conditionals: GrammarCategory = {
  id: 'conditionals',
  language: 'en',
  title: 'Умовні речення та умовний спосіб',
  description:
    'Чотири базові типи умовних речень, їхні змішані варіанти, формальна інверсія замість if, а також бажання, жаль і сослагательний спосіб — усе, що описує нереальні, гіпотетичні чи умовні ситуації.',
  topics: [
    {
      id: 'zero-first-conditional',
      title: 'Zero and First Conditional',
      theory:
        'Zero Conditional (if + Present Simple, Present Simple) описує загальні істини та закономірності, що завжди правдиві — науковий факт чи логічний наслідок, де if можна замінити на when без зміни змісту. First Conditional (if + Present Simple, will + інфінітив) описує реальну, цілком імовірну ситуацію в майбутньому та її наслідок. У обох типах after if вживається Present Simple, а не will, навіть коли йдеться про майбутнє — це типова помилка українських мовців, що калькують "якщо буде".',
      examples: [
        { target: 'If you heat ice, it melts.', uk: 'Якщо нагріти лід, він тане (загальна істина).' },
        { target: "If it rains tomorrow, we'll stay at home.", uk: 'Якщо завтра піде дощ, ми залишимось вдома (реальна майбутня умова).' },
        { target: "If you don't water plants, they die.", uk: 'Якщо не поливати рослини, вони гинуть (закономірність).' },
      ],
      exercises: [
        {
          id: 'zfc-1',
          type: 'multiple-choice',
          prompt: 'If you mix red and blue, you ___ purple.',
          options: ['get', 'will get', 'got', 'would get'],
          correctIndex: 0,
          explanation: 'Zero Conditional: if + Present Simple, Present Simple — загальна закономірність.',
        },
        {
          id: 'zfc-2',
          type: 'multiple-choice',
          prompt: "If it ___ tomorrow, we'll cancel the picnic.",
          options: ['will rain', 'rains', 'rained', 'would rain'],
          correctIndex: 1,
          explanation: "Після if у First Conditional вживається Present Simple, навіть коли йдеться про майбутнє (не 'will rain').",
        },
        {
          id: 'zfc-3',
          type: 'fill-blank',
          prompt: 'If you ___ (heat) water to 100°C, it boils.',
          correctAnswers: ['heat'],
          explanation: 'Zero Conditional описує науковий факт: if + Present Simple.',
        },
        {
          id: 'zfc-4',
          type: 'fill-blank',
          prompt: "If she ___ (study) hard, she will pass the exam.",
          correctAnswers: ['studies'],
          explanation: "First Conditional: реальна майбутня умова, у if-частині — Present Simple.",
        },
        {
          id: 'zfc-5',
          type: 'multiple-choice',
          prompt: 'Which sentence can naturally replace "if" with "when" without changing the meaning?',
          options: [
            'If you heat ice, it melts.',
            'If I win the lottery, I will travel the world.',
            'If she calls tonight, I will tell her the news.',
            'If it rains tomorrow, we will stay home.',
          ],
          correctIndex: 0,
          explanation: 'Zero Conditional описує завжди правдиву закономірність — if тут рівнозначне when.',
        },
      ],
    },
    {
      id: 'second-conditional',
      title: 'Second Conditional',
      theory:
        'Second Conditional (if + Past Simple, would + інфінітив) описує гіпотетичну, нереальну або малоймовірну ситуацію в теперішньому чи майбутньому — те, чого немає зараз, або те, що малоймовірне. Минулий час тут не означає минулий момент, а лише сигналізує нереальність. У формальному стилі для всіх осіб (включно з I/he/she) прийнято вживати were замість was: "If I were you, I would apologise."',
      examples: [
        { target: 'If I won the lottery, I would buy a house.', uk: 'Якби я виграв лотерею, я б купив будинок (гіпотетично, малоймовірно).' },
        { target: 'If I were you, I would apologise.', uk: 'На твоєму місці я б вибачився (were для всіх осіб у формальному стилі).' },
        { target: "If she spoke German, she'd get the job.", uk: 'Якби вона розмовляла німецькою, вона отримала б цю роботу (зараз не розмовляє).' },
      ],
      exercises: [
        {
          id: 'sc-1',
          type: 'multiple-choice',
          prompt: 'If I ___ more time, I would learn to play the piano.',
          options: ['have', 'had', 'will have', 'would have'],
          correctIndex: 1,
          explanation: 'Second Conditional: if + Past Simple (had) для гіпотетичного теперішнього.',
        },
        {
          id: 'sc-2',
          type: 'multiple-choice',
          prompt: 'If I ___ you, I would take that job offer.',
          options: ['was', 'am', 'were', 'be'],
          correctIndex: 2,
          explanation: 'У формальному стилі "If I were you" — were вживається для всіх осіб.',
        },
        {
          id: 'sc-3',
          type: 'fill-blank',
          prompt: 'If he ___ (know) the truth, he would tell us.',
          correctAnswers: ['knew'],
          explanation: 'Second Conditional: Past Simple після if позначає нереальний теперішній стан.',
        },
        {
          id: 'sc-4',
          type: 'fill-blank',
          prompt: "She ___ (help) you if she weren't so busy right now.",
          correctAnswers: ['would help'],
          explanation: 'У головній частині — would + інфінітив без to.',
        },
        {
          id: 'sc-5',
          type: 'multiple-choice',
          prompt: 'Which situation is a typical use of the Second Conditional?',
          options: [
            'A scientific fact that is always true.',
            'A realistic plan for tomorrow.',
            'A hypothetical, unlikely situation right now.',
            'A regret about something in the past.',
          ],
          correctIndex: 2,
          explanation: 'Second Conditional описує гіпотетичну/малоймовірну ситуацію в теперішньому чи майбутньому.',
        },
      ],
    },
    {
      id: 'third-conditional',
      title: 'Third Conditional',
      theory:
        'Third Conditional (if + Past Perfect, would have + V3) описує нереальну ситуацію в минулому та її нереальний наслідок — те, чого насправді не сталося. Використовується для жалю чи розмірковувань "а що якби": подія в if-частині вже відбулася (чи не відбулася) остаточно, і змінити це неможливо.',
      examples: [
        { target: "If I had known about the traffic, I would have left earlier.", uk: 'Якби я знав про затори, я виїхав би раніше (але не знав, тому запізнився).' },
        { target: "If she had studied medicine, she would have become a doctor.", uk: 'Якби вона вивчала медицину, вона стала б лікарем (не вивчала).' },
        { target: "We wouldn't have missed the flight if we had left on time.", uk: 'Ми не запізнилися б на рейс, якби виїхали вчасно (запізнились).' },
      ],
      exercises: [
        {
          id: 'tc-1',
          type: 'multiple-choice',
          prompt: 'If I ___ earlier, I would have caught the train.',
          options: ['left', 'had left', 'would leave', 'leave'],
          correctIndex: 1,
          explanation: 'Third Conditional: if + Past Perfect (had left) для нереального минулого.',
        },
        {
          id: 'tc-2',
          type: 'multiple-choice',
          prompt: "She would have passed the exam if she ___ harder.",
          options: ['studied', 'had studied', 'has studied', 'studies'],
          correctIndex: 1,
          explanation: 'If + Past Perfect у підрядній частині Third Conditional.',
        },
        {
          id: 'tc-3',
          type: 'fill-blank',
          prompt: 'If we ___ (know) about the storm, we would not have gone sailing.',
          correctAnswers: ['had known'],
          explanation: 'Past Perfect після if позначає нереальну умову в минулому.',
        },
        {
          id: 'tc-4',
          type: 'fill-blank',
          prompt: "I ___ (call) you if I had had your number.",
          correctAnswers: ['would have called'],
          explanation: 'Головна частина Third Conditional: would have + V3.',
        },
        {
          id: 'tc-5',
          type: 'multiple-choice',
          prompt: 'Which of these expresses a regret about something that did NOT happen in the past?',
          options: [
            'If it rains, I will stay home.',
            'If I were rich, I would travel more.',
            'If I had worked harder, I would have got the promotion.',
            'If you heat metal, it expands.',
          ],
          correctIndex: 2,
          explanation: 'Third Conditional описує нереальну минулу подію і жаль за нею.',
        },
      ],
    },
    {
      id: 'mixed-conditionals',
      title: 'Mixed Conditionals',
      theory:
        'Змішані умовні речення поєднують часові плани, коли причина й наслідок стосуються різних періодів. Найпоширеніший тип: минула нереальна причина → теперішній нереальний результат (if + Past Perfect, would + інфінітив): "If I had studied medicine, I would be a doctor now" — рішення в минулому досі впливає на теперішнє. Рідше трапляється й зворотний варіант: загальна/теперішня нереальна риса → минулий нереальний результат (if + Past Simple, would have + V3): "If she weren\'t so shy, she would have spoken up yesterday" — її характер (постійна риса) вплинув на конкретну минулу подію.',
      examples: [
        { target: "If I had studied medicine, I would be a doctor now.", uk: 'Якби я вивчав медицину, я був би зараз лікарем (минуле рішення → теперішній результат).' },
        { target: "If she weren't so shy, she would have spoken up at the meeting yesterday.", uk: 'Якби вона не була такою сором\'язливою, вона висловилась би на вчорашній зустрічі (постійна риса → минулий результат).' },
        { target: "If he hadn't missed the flight, he would be here with us now.", uk: 'Якби він не запізнився на рейс, він був би зараз тут з нами.' },
      ],
      exercises: [
        {
          id: 'mc-1',
          type: 'multiple-choice',
          prompt: "If I ___ harder at university, I would have a much better job now.",
          options: ['worked', 'had worked', 'would work', 'work'],
          correctIndex: 1,
          explanation: 'Минула нереальна причина (if + Past Perfect) → теперішній результат (would + інфінітив).',
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          prompt: "If she weren't so stubborn, she ___ his advice yesterday.",
          options: ['would take', 'would have taken', 'took', 'takes'],
          correctIndex: 1,
          explanation: 'Постійна риса характеру (if + Past Simple) → нереальний минулий результат (would have + V3).',
        },
        {
          id: 'mc-3',
          type: 'fill-blank',
          prompt: "If we ___ (buy) that house, we would be much richer today.",
          correctAnswers: ['had bought'],
          explanation: 'Минуле рішення (Past Perfect) впливає на теперішній нереальний стан.',
        },
        {
          id: 'mc-4',
          type: 'fill-blank',
          prompt: "If he weren't so careless, he ___ (lose) his wallet last week.",
          correctAnswers: ["wouldn't have lost", 'would not have lost'],
          explanation: 'Загальна риса (careless) у теперішньому пояснює конкретний минулий наслідок.',
        },
        {
          id: 'mc-5',
          type: 'multiple-choice',
          prompt: 'Which sentence is a mixed conditional linking a past cause to a present result?',
          options: [
            'If I had left earlier, I would have caught the train.',
            'If I had taken that job, I would be living in Berlin now.',
            'If I were taller, I would play basketball.',
            'If it rains, the match will be cancelled.',
          ],
          correctIndex: 1,
          explanation: 'Past Perfect у причині + would (не would have) у наслідку — минуле рішення досі впливає на теперішнє.',
        },
      ],
    },
    {
      id: 'alternatives-to-if',
      title: 'Alternatives to "if" (as long as, provided/providing, unless, in case, but for, supposing)',
      theory:
        'Кілька виразів заміняють if, додаючи нюанс. As long as / provided (that) / providing (that) означають "за умови, що" й підкреслюють обов\'язкову умову, часто у формальному стилі. Unless означає "якщо не" (= if...not), але не завжди взаємозамінне з усіма запереченнями: unless вживають для єдиної винятковiї умови, а не для гіпотетичного заперечення (порівняйте: "I\'ll come unless it rains" природно, але "*I would help unless you asked" звучить дивно — тут потрібне if...didn\'t). In case вводить запобіжний захід ("про всяк випадок"), а не умову: "Take an umbrella in case it rains" означає взяти парасольку заздалегідь, незалежно від того, піде дощ чи ні — це не те саме, що "if it rains". But for + іменник означає "якби не" і вказує на єдину причину, що змінила б результат.',
      examples: [
        { target: "You can borrow my car as long as you fill up the tank.", uk: 'Можеш взяти мою машину за умови, що заправиш бак.' },
        { target: "I'll be there unless something urgent comes up.", uk: 'Я буду там, якщо не станеться щось термінове.' },
        { target: "Take your phone in case you get lost.", uk: 'Візьми телефон про всяк випадок, якщо загубишся (запобіжний захід, не умова).' },
      ],
      exercises: [
        {
          id: 'ati-1',
          type: 'multiple-choice',
          prompt: 'You can stay out late ___ you call us when you arrive.',
          options: ['unless', 'as long as', 'in case', 'but for'],
          correctIndex: 1,
          explanation: 'As long as вводить обов\'язкову умову: "за умови, що".',
        },
        {
          id: 'ati-2',
          type: 'multiple-choice',
          prompt: "I always carry a spare key ___ I lock myself out.",
          options: ['unless', 'provided', 'in case', 'as long as'],
          correctIndex: 2,
          explanation: 'In case означає запобіжний захід, а не умову — носять ключ заздалегідь на випадок.',
        },
        {
          id: 'ati-3',
          type: 'fill-blank',
          prompt: "___ his help, we would never have finished the project on time.",
          correctAnswers: ['But for'],
          explanation: 'But for + іменник — "якби не" (єдина причина іншого результату).',
        },
        {
          id: 'ati-4',
          type: 'fill-blank',
          prompt: "We'll go hiking tomorrow ___ (unless) it rains.",
          correctAnswers: ['unless'],
          explanation: 'Unless = if...not: "якщо не піде дощ".',
        },
        {
          id: 'ati-5',
          type: 'multiple-choice',
          prompt: "Which sentence correctly uses 'in case' (a precaution, not a condition)?",
          options: [
            'I will call you in case you need anything, so call me if you do.',
            'I will bring a jacket in case it gets cold — better safe than sorry.',
            'In case it rains, we will go to the beach.',
            'I will help you in case you ask me to.',
          ],
          correctIndex: 1,
          explanation: 'In case описує запобіжну дію заздалегідь, незалежно від того, чи станеться подія.',
        },
      ],
    },
    {
      id: 'inversion-in-conditionals',
      title: 'Inversion in Conditionals (Had I known..., Were I you..., Should you need...)',
      theory:
        'У формальному чи літературному стилі if можна опустити, переставивши допоміжне дієслово на початок речення (інверсія). Had + підмет + V3 замінює third conditional if-частину: "Had I known, I would have called." Were + підмет замінює second conditional з were: "Were I you, I would apologise." Should + підмет + інфінітив замінює first conditional для малоймовірної, гіпотетичної умови: "Should you need anything, let me know." Ця конструкція типова для офіційних листів, договорів і літературного стилю.',
      examples: [
        { target: "Had I known about the meeting, I would have attended.", uk: 'Якби я знав про зустріч, я б прийшов (формальна інверсія замість if I had known).' },
        { target: "Were I you, I would think twice.", uk: 'На твоєму місці я б подумав двічі (замість if I were you).' },
        { target: "Should you need any assistance, please contact us.", uk: 'Якщо вам знадобиться допомога, звертайтесь до нас (офіційний тон).' },
      ],
      exercises: [
        {
          id: 'iic-1',
          type: 'multiple-choice',
          prompt: 'Choose the formal inversion of: "If I had known, I would have helped."',
          options: [
            'Had I known, I would have helped.',
            'Have I known, I would have helped.',
            'Did I know, I would have helped.',
            'I had known, I would have helped.',
          ],
          correctIndex: 0,
          explanation: 'Third conditional inversion: Had + підмет + V3, без if.',
        },
        {
          id: 'iic-2',
          type: 'multiple-choice',
          prompt: 'Choose the formal inversion of: "If you should need help, call this number."',
          options: [
            'Should you need help, call this number.',
            'Would you need help, call this number.',
            'Do you need help, call this number.',
            'Needed you help, call this number.',
          ],
          correctIndex: 0,
          explanation: 'Should + підмет + інфінітив замінює if you should для малоймовірної умови.',
        },
        {
          id: 'iic-3',
          type: 'fill-blank',
          prompt: "___ I richer, I would buy that house. (formal inversion of 'If I were richer')",
          correctAnswers: ['Were'],
          explanation: 'Were + підмет замінює if I were у формальному стилі.',
        },
        {
          id: 'iic-4',
          type: 'fill-blank',
          prompt: "___ she arrived earlier, she would have met him. (formal inversion of 'If she had arrived')",
          correctAnswers: ['Had'],
          explanation: 'Had + підмет + V3 — інверсія third conditional.',
        },
        {
          id: 'iic-5',
          type: 'multiple-choice',
          prompt: 'In which style is inverted conditional (without "if") most typical?',
          options: ['Casual texting between friends', 'Formal writing, contracts, literary style', 'Children\'s books', 'Slang expressions'],
          correctIndex: 1,
          explanation: 'Інверсія замість if — ознака формального або літературного стилю.',
        },
      ],
    },
    {
      id: 'wishes-and-regrets',
      title: 'Wishes and Regrets (I wish / If only)',
      theory:
        'Wish/if only + Past Simple виражає бажання змінити теперішню ситуацію (нереальний теперішній стан): "I wish I spoke French" (я не розмовляю французькою зараз). Wish/if only + Past Perfect виражає жаль за минулим: "I wish I had studied harder" (я не вчився старанно тоді). Wish + would + інфінітив висловлює роздратування чужою поведінкою чи бажання, щоб ситуація змінилась (не про самого мовця): "I wish you would stop smoking." If only звучить емоційнішим і сильнішим за wish, часто зі знаком оклику.',
      examples: [
        { target: "I wish I spoke German fluently.", uk: 'Шкода, що я не розмовляю вільно німецькою (нереальний теперішній стан).' },
        { target: "I wish I had visited Paris when I had the chance.", uk: 'Шкода, що я не відвідав Париж, коли мав таку можливість (жаль про минуле).' },
        { target: "I wish you would stop interrupting me!", uk: 'Хотів би я, щоб ти перестав мене перебивати! (роздратування чужою поведінкою).' },
      ],
      exercises: [
        {
          id: 'war-1',
          type: 'multiple-choice',
          prompt: 'I wish I ___ how to swim.',
          options: ['know', 'knew', 'had known', 'would know'],
          correctIndex: 1,
          explanation: 'Wish + Past Simple — бажання змінити нинішній стан (зараз не вмію плавати).',
        },
        {
          id: 'war-2',
          type: 'multiple-choice',
          prompt: 'I wish I ___ so rude to her yesterday.',
          options: ["wasn't", "hadn't been", "haven't been", "won't be"],
          correctIndex: 1,
          explanation: 'Wish + Past Perfect — жаль про конкретну минулу дію.',
        },
        {
          id: 'war-3',
          type: 'fill-blank',
          prompt: 'I wish you ___ (stop) leaving your clothes on the floor!',
          correctAnswers: ['would stop'],
          explanation: 'Wish + would виражає роздратування чужою повторюваною поведінкою.',
        },
        {
          id: 'war-4',
          type: 'fill-blank',
          prompt: "If only I ___ (study) harder for that exam last year.",
          correctAnswers: ['had studied'],
          explanation: 'If only + Past Perfect — сильний жаль про минуле.',
        },
        {
          id: 'war-5',
          type: 'multiple-choice',
          prompt: 'Which sentence expresses irritation about someone else\'s behaviour?',
          options: [
            'I wish I were taller.',
            'I wish I had left earlier.',
            'I wish you would listen to me for once.',
            'I wish it were summer.',
          ],
          correctIndex: 2,
          explanation: 'Wish + would + інфінітив — типово для скарги на поведінку іншої людини.',
        },
      ],
    },
    {
      id: 'unreal-time',
      title: "Unreal Time after it's time, would rather, as if/though",
      theory:
        "Деякі вирази вимагають форми минулого часу для опису чогось умовно теперішнього чи гіпотетичного, а не реального минулого. It's time + Past Simple (не інфінітив) означає, що щось давно пора зробити зараз: \"It's time we left\" (нам уже час іти). Would rather + Past Simple описує бажання, щоб хтось інший зробив/не зробив щось саме зараз: \"I'd rather you didn't tell him\" (коли підмети різні; якщо підмет той самий — просто would rather + bare infinitive: I'd rather stay). As if / as though + Past Simple (чи Past Perfect для ще ранішого) вводить нереальне порівняння: \"She talks as if she owned the place\" (насправді не володіє).",
      examples: [
        { target: "It's time we left — the film starts in ten minutes.", uk: 'Нам уже час іти — фільм починається за десять хвилин.' },
        { target: "I'd rather you didn't tell him about this.", uk: 'Я б хотів, щоб ти йому про це не розповідав.' },
        { target: "He talks as if he knew everything.", uk: 'Він говорить так, ніби знає все (насправді не знає).' },
      ],
      exercises: [
        {
          id: 'ut-1',
          type: 'multiple-choice',
          prompt: "It's time you ___ your homework — it's already 9 p.m.",
          options: ['do', 'did', 'have done', 'will do'],
          correctIndex: 1,
          explanation: "It's time + Past Simple — умовно теперішнє значення 'давно пора'.",
        },
        {
          id: 'ut-2',
          type: 'multiple-choice',
          prompt: "I'd rather you ___ smoke in here.",
          options: ["don't", "didn't", "won't", "not"],
          correctIndex: 1,
          explanation: "Would rather + інший підмет + Past Simple — бажання щодо чужої дії зараз.",
        },
        {
          id: 'ut-3',
          type: 'fill-blank',
          prompt: "She acts as if she ___ (be) the boss around here.",
          correctAnswers: ['were', 'was'],
          explanation: 'As if + Past Simple — нереальне порівняння в теперішньому.',
        },
        {
          id: 'ut-4',
          type: 'fill-blank',
          prompt: "It's high time we ___ (change) our old car.",
          correctAnswers: ['changed'],
          explanation: "It's (high) time + Past Simple — давно пора це зробити.",
        },
        {
          id: 'ut-5',
          type: 'multiple-choice',
          prompt: 'Which sentence correctly uses "as if" for an unreal comparison?',
          options: [
            'He looks as if he is tired today, which is true.',
            'She spends money as if she was a millionaire, but she isn\'t.',
            'He runs as if he is in a hurry, and he really is.',
            'It looks as if it will rain, and it probably will.',
          ],
          correctIndex: 1,
          explanation: "As if вводить нереальне порівняння — вона насправді не мільйонерка.",
        },
      ],
    },
    {
      id: 'subjunctive',
      title: 'The Subjunctive (suggest that he be, it\'s essential that she attend)',
      theory:
        'Сослагательний спосіб (mandative subjunctive) вживається після дієслів-наказів/пропозицій (suggest, recommend, insist, demand, propose) і прикметників необхідності (essential, vital, important, necessary) у конструкції that + підмет + базова форма дієслова, незалежно від особи чи часу: "I suggest that he be more careful" (не "is"), "It is essential that she attend the meeting" (не "attends"). Це особливо поширено в американській та формальній англійській; у британській розмовній мові частіше вживають альтернативу з should: "I suggest that he should be more careful."',
      examples: [
        { target: 'The doctor recommended that he rest for a week.', uk: 'Лікар порадив, щоб він відпочивав тиждень (базова форма rest, не rests).' },
        { target: 'It is essential that every student attend the lecture.', uk: 'Важливо, щоб кожен студент відвідав лекцію.' },
        { target: 'She insisted that he apologise immediately.', uk: 'Вона наполягла, щоб він негайно вибачився.' },
      ],
      exercises: [
        {
          id: 'sub-1',
          type: 'multiple-choice',
          prompt: 'The manager suggested that she ___ the report again.',
          options: ['checks', 'checked', 'check', 'will check'],
          correctIndex: 2,
          explanation: 'Mandative subjunctive: that + підмет + базова форма (check), незалежно від особи.',
        },
        {
          id: 'sub-2',
          type: 'multiple-choice',
          prompt: 'It is vital that every passenger ___ their seatbelt.',
          options: ['wears', 'wear', 'wearing', 'wore'],
          correctIndex: 1,
          explanation: 'Після essential/vital + that — базова форма дієслова (wear), навіть з every passenger (однина).',
        },
        {
          id: 'sub-3',
          type: 'fill-blank',
          prompt: "I demand that he ___ (leave) the room at once.",
          correctAnswers: ['leave'],
          explanation: 'Demand + that + базова форма дієслова — mandative subjunctive.',
        },
        {
          id: 'sub-4',
          type: 'fill-blank',
          prompt: "The committee recommended that the policy ___ (be) reviewed.",
          correctAnswers: ['be'],
          explanation: "Навіть дієслово be у сослагательному способі лишається в базовій формі: be, не is/was.",
        },
        {
          id: 'sub-5',
          type: 'multiple-choice',
          prompt: "Which sentence correctly uses the mandative subjunctive?",
          options: [
            'It is important that he arrives on time.',
            'It is important that he arrive on time.',
            'It is important that he arrived on time.',
            'It is important that he will arrive on time.',
          ],
          correctIndex: 1,
          explanation: 'Базова форма arrive (без -s), незважаючи на he — типова ознака сослагательного способу.',
        },
      ],
    },
  ],
}
