// Types
import type { GrammarCategory } from '@/types/grammarTopic'

export const partsOfSpeech: GrammarCategory = {
  id: 'parts-of-speech',
  title: 'Частини мови та їхні нюанси',
  description:
    'Артиклі, визначники й квантифікатори, займенники, іменники, прикметники/прислівники та прийменники — деталі, які найчастіше видають нерідного мовця, навіть коли базова граматика вже засвоєна.',
  topics: [
    {
      id: 'articles',
      title: 'Articles (a/an, the, and the Zero Article)',
      theory:
        'A/an вживається при першій згадці предмета чи коли він один із багатьох ("I saw a dog"). The вживається, коли річ уже відома зі контексту, згадувалась раніше, або є єдиною у своєму роді ("the sun", "the dog I mentioned"). Нульовий артикль вживається з незлічуваними/множинними іменниками в загальному значенні ("I like music", "Dogs are loyal") та з більшістю власних назв (imена людей, більшість країн, вулиць), а також у стійких виразах на кшталт "go to school/work/bed" (у їхньому типовому, функціональному значенні, без the). Географічні назви мають свої правила: гори/континенти/озера/більшість країн — без the (Mount Everest, Lake Baikal), але океани, річки, групи островів, гірські пасма й країни з "of"/множинною формою в назві — з the (the Pacific, the Alps, the United States).',
      examples: [
        { en: 'I bought a book yesterday. The book was fascinating.', uk: 'Я купив книгу вчора. Книга (та сама) виявилась захопливою.' },
        { en: 'Dogs make great companions.', uk: 'Собаки — чудові компаньйони (загальне твердження, нульовий артикль).' },
        { en: 'We climbed Mount Everest, but he lives near the Alps.', uk: 'Ми піднялися на Еверест, а він живе біля Альп (гора без the, гірське пасмо — з the).' },
      ],
      exercises: [
        {
          id: 'art-1',
          type: 'multiple-choice',
          prompt: 'I saw ___ interesting film last night. ___ film was about space travel.',
          options: ['a / A', 'a / The', 'the / A', 'the / The'],
          correctIndex: 1,
          explanation: 'Перша згадка → a; повторна згадка того самого предмета → the.',
        },
        {
          id: 'art-2',
          type: 'multiple-choice',
          prompt: 'Choose the correct sentence.',
          options: ['I go to the school every day.', 'I go to school every day.', 'I go to a school every day.', 'I go school every day.'],
          correctIndex: 1,
          explanation: '"Go to school" у типовому функціональному значенні (навчатись) — без артикля.',
        },
        {
          id: 'art-3',
          type: 'fill-blank',
          prompt: '___ Nile is the longest river in Africa. (choose: the / a / — no article)',
          correctAnswers: ['The'],
          explanation: 'Річки вживаються з означеним артиклем: the Nile.',
        },
        {
          id: 'art-4',
          type: 'fill-blank',
          prompt: 'She lives in ___ (no article needed) France, near ___ Pyrenees.',
          correctAnswers: ['the'],
          explanation: 'Більшість країн — без артикля (France), але гірські пасма — з the (the Pyrenees).',
        },
        {
          id: 'art-5',
          type: 'multiple-choice',
          prompt: 'Which sentence correctly uses the zero article for a general statement?',
          options: ['The cats are independent animals in general.', 'Cats are independent animals in general.', 'A cats are independent animals.', 'The cat are independent animals.'],
          correctIndex: 1,
          explanation: 'Загальне твердження про клас істот у множині — без артикля.',
        },
      ],
    },
    {
      id: 'determiners-quantifiers',
      title: 'Determiners and Quantifiers (some, any, every, each, either, neither, few/little)',
      theory:
        'Some зазвичай вживається в стверджувальних реченнях і в питаннях-пропозиціях/проханнях ("Would you like some tea?"), тоді як any типове для питань і заперечень ("Do you have any milk? I don\'t have any"). Every розглядає групу як єдине ціле й вживається з дієсловом в однині ("Every student has a book"), тоді як each підкреслює кожного члена групи окремо, часто коли їх небагато ("Each student received a certificate individually"). Either/neither вживаються лише з двома предметами (either вибір з двох, neither — заперечення обох), на відміну від any/none, які підходять для трьох і більше. Few/little (без a) мають негативний відтінок — "майже немає, недостатньо", тоді як a few/a little — позитивний відтінок "трохи є, достатньо".',
      examples: [
        { en: 'Would you like some coffee?', uk: 'Хочеш кави? (пропозиція, some у питанні).' },
        { en: "I have few friends here — I feel quite lonely.", uk: 'У мене тут мало друзів — я почуваюсь доволі самотнім (few, негативний відтінок).' },
        { en: "I have a few friends here, so it's not too bad.", uk: 'У мене тут є декілька друзів, тож не так уже й погано (a few, позитивний відтінок).' },
      ],
      exercises: [
        {
          id: 'dq-1',
          type: 'multiple-choice',
          prompt: "I don't have ___ money left.",
          options: ['some', 'any', 'every', 'each'],
          correctIndex: 1,
          explanation: 'Any типове для заперечних речень.',
        },
        {
          id: 'dq-2',
          type: 'multiple-choice',
          prompt: '___ student in the class passed the exam — all of them, one by one.',
          options: ['Every', 'Each', 'All', 'Some'],
          correctIndex: 1,
          explanation: 'Each підкреслює кожного окремо, особливо коли групу невелика і важлива індивідуальність.',
        },
        {
          id: 'dq-3',
          type: 'fill-blank',
          prompt: "She has ___ (little) time, so she rarely relaxes. (negative implication: almost no time)",
          correctAnswers: ['little'],
          explanation: 'Little (без a) — негативний відтінок "майже немає".',
        },
        {
          id: 'dq-4',
          type: 'fill-blank',
          prompt: 'There are only two roads — you can take ___ of them.',
          correctAnswers: ['either'],
          explanation: 'Either вживається лише з вибором з двох варіантів.',
        },
        {
          id: 'dq-5',
          type: 'multiple-choice',
          prompt: 'Which sentence has a positive implication ("some, enough")?',
          options: [
            'I have little hope of passing this test.',
            'I have a little hope of passing this test.',
            'There is little water left in the bottle.',
            'Few people showed up to the event.',
          ],
          correctIndex: 1,
          explanation: 'A little має позитивний відтінок — "трохи, але є".',
        },
      ],
    },
    {
      id: 'pronouns',
      title: 'Pronouns (subject, object, possessive, reflexive, relative)',
      theory:
        'Англійська розрізняє п\'ять типів займенників: підметові (I, you, he, she, it, we, they), додаткові (me, you, him, her, it, us, them), присвійні (mine, yours, his, hers, its, ours, theirs — самостійні, без іменника поруч, на відміну від присвійних прикметників my/your/his), зворотні (myself, yourself, himself... — коли підмет і об\'єкт дії збігаються) і відносні (who/whom для людей, which для речей, whose для присвійності, that для обох у обмежувальних реченнях). Типова помилка — плутати myself із просто me ("give it to myself" неправильно, треба "give it to me", бо me не є тим самим, хто виконує дію), а also who/whom: who — підмет, whom — додаток (формально), хоча в розмовній мові who часто заміняє обидва.',
      examples: [
        { en: 'She bought herself a new phone.', uk: 'Вона купила собі новий телефон (зворотний займенник, підмет=об\'єкт).' },
        { en: 'This book is mine, not yours.', uk: 'Ця книга моя, не твоя (присвійні займенники, самостійні).' },
        { en: 'The man who called you is my uncle.', uk: 'Чоловік, який тобі дзвонив, — мій дядько (відносний займенник who для людини-підмета).' },
      ],
      exercises: [
        {
          id: 'pro-1',
          type: 'multiple-choice',
          prompt: 'He hurt ___ while playing football.',
          options: ['him', 'himself', 'he', 'his'],
          correctIndex: 1,
          explanation: 'Зворотний займенник himself, бо підмет і об\'єкт дії — одна й та сама особа.',
        },
        {
          id: 'pro-2',
          type: 'multiple-choice',
          prompt: 'This isn\'t my umbrella — it must be ___.',
          options: ['her', 'hers', 'she', 'herself'],
          correctIndex: 1,
          explanation: 'Присвійний займенник hers вживається самостійно, без іменника поруч.',
        },
        {
          id: 'pro-3',
          type: 'fill-blank',
          prompt: 'The woman ___ car was stolen called the police.',
          correctAnswers: ['whose'],
          explanation: 'Whose — відносний займенник для присвійності.',
        },
        {
          id: 'pro-4',
          type: 'fill-blank',
          prompt: 'Can you give the documents to ___ (me/myself)?',
          correctAnswers: ['me'],
          explanation: 'Об\'єктний займенник me, бо той, хто дає, і той, хто отримує, — різні особи.',
        },
        {
          id: 'pro-5',
          type: 'multiple-choice',
          prompt: 'Which sentence correctly uses a relative pronoun for a person as the object of the clause?',
          options: [
            'The man which I met is a doctor.',
            'The man whom I met is a doctor.',
            'The man whose I met is a doctor.',
            'The man who I met is are a doctor.',
          ],
          correctIndex: 1,
          explanation: 'Whom (формально) вживається для людини-додатка в підрядному реченні.',
        },
      ],
    },
    {
      id: 'nouns-countable-uncountable',
      title: 'Countable and Uncountable Nouns',
      theory:
        'Злічувані іменники мають форму однини й множини (a book/books) і можуть вживатись з числівниками та a/an. Незлічувані іменники (advice, information, furniture, news, luggage, homework) сприймаються як єдина маса й НЕ мають множини — типова помилка українських мовців: "*informations", "*advices", "*furnitures". Множина деяких іменників утворюється нестандартно: child→children, mouse→mice, man→men, foot→feet, person→people, а деякі іменники (sheep, fish, series) мають однакову форму в однині й множині. Складні іменники (compound nouns) зазвичай додають -s лише до останнього слова (bookshops, websites), хоча є винятки (mothers-in-law, де -s додається до головного слова).',
      examples: [
        { en: "Can you give me some advice?", uk: 'Можеш дати мені пораду? (advice — незлічуваний, без a і без -s).' },
        { en: "I saw three sheep in the field.", uk: 'Я побачив трьох овець у полі (sheep — однакова форма в однині й множині).' },
        { en: "My mother-in-law is visiting us.", uk: 'До нас приїжджає моя теща (складний іменник, множина: mothers-in-law).' },
      ],
      exercises: [
        {
          id: 'nc-1',
          type: 'multiple-choice',
          prompt: 'Choose the correct sentence.',
          options: ['I need some informations.', 'I need some information.', 'I need an information.', 'I need informations.'],
          correctIndex: 1,
          explanation: 'Information — незлічуваний іменник, не має множини й не вживається з a/an.',
        },
        {
          id: 'nc-2',
          type: 'multiple-choice',
          prompt: 'There were many ___ playing in the park.',
          options: ['childs', 'children', 'child', 'childrens'],
          correctIndex: 1,
          explanation: 'Child має нестандартну множину: children.',
        },
        {
          id: 'nc-3',
          type: 'fill-blank',
          prompt: 'I saw two ___ (mouse) in the kitchen.',
          correctAnswers: ['mice'],
          explanation: 'Mouse має нестандартну множину: mice.',
        },
        {
          id: 'nc-4',
          type: 'fill-blank',
          prompt: 'She gave me a useful piece of ___ (advice).',
          correctAnswers: ['advice'],
          explanation: 'Advice незлічуваний — кількість виражається через "a piece of advice".',
        },
        {
          id: 'nc-5',
          type: 'multiple-choice',
          prompt: 'Which noun is uncountable in English (unlike its Ukrainian equivalent)?',
          options: ['book', 'chair', 'furniture', 'apple'],
          correctIndex: 2,
          explanation: 'Furniture — незлічуваний іменник в англійській, хоча в українській "меблі" сприймається як множина.',
        },
      ],
    },
    {
      id: 'adjectives-adverbs-comparison',
      title: 'Adjectives, Adverbs, and Comparison',
      theory:
        'Коли кілька прикметників стоять перед іменником, вони йдуть у типовому порядку: думка (opinion) → розмір (size) → вік (age) → форма (shape) → колір (colour) → походження (origin) → матеріал (material) → призначення (purpose) + іменник ("a beautiful small old round black Italian wooden dining table" — хоча на практиці рідко використовують стільки одразу). Короткі прикметники (1 склад, деякі 2-складові) утворюють порівняльний ступінь через -er/-est (tall→taller→tallest), довші — через more/most (expensive→more expensive→most expensive). Подвійний порівняльний зворот "the more..., the better/more..." виражає пропорційну залежність двох явищ: "The more you practice, the better you get."',
      examples: [
        { en: 'She bought a beautiful antique French vase.', uk: 'Вона купила красиву старовинну французьку вазу (порядок: думка-вік-походження).' },
        { en: 'This exercise is more difficult than the last one.', uk: 'Ця вправа складніша за попередню (довгий прикметник → more).' },
        { en: 'The more you read, the more you know.', uk: 'Чим більше читаєш, тим більше знаєш (подвійний порівняльний зворот).' },
      ],
      exercises: [
        {
          id: 'aac-1',
          type: 'multiple-choice',
          prompt: 'Choose the sentence with the correct adjective order.',
          options: [
            'A red small bag.',
            'A small red bag.',
            'A bag small red.',
            'A red bag small.',
          ],
          correctIndex: 1,
          explanation: 'Порядок: розмір (small) перед кольором (red).',
        },
        {
          id: 'aac-2',
          type: 'multiple-choice',
          prompt: 'This is the ___ book I have ever read.',
          options: ['more interesting', 'most interesting', 'interestingest', 'interesting'],
          correctIndex: 1,
          explanation: 'Довгий прикметник interesting утворює найвищий ступінь через most.',
        },
        {
          id: 'aac-3',
          type: 'fill-blank',
          prompt: 'She runs ___ (fast) than her brother.',
          correctAnswers: ['faster'],
          explanation: 'Короткий прикметник/прислівник fast → -er у порівняльному ступені.',
        },
        {
          id: 'aac-4',
          type: 'fill-blank',
          prompt: 'The ___ (early) you leave, the ___ (early) you arrive.',
          correctAnswers: ['earlier, earlier'],
          explanation: 'Подвійний порівняльний зворот "the + comparative..., the + comparative...".',
        },
        {
          id: 'aac-5',
          type: 'multiple-choice',
          prompt: 'Which sentence follows the standard adjective order (opinion-age-material)?',
          options: [
            'A wooden lovely old chair.',
            'A lovely old wooden chair.',
            'An old wooden lovely chair.',
            'A wooden old lovely chair.',
          ],
          correctIndex: 1,
          explanation: 'Порядок: думка (lovely) → вік (old) → матеріал (wooden).',
        },
      ],
    },
    {
      id: 'prepositions',
      title: 'Prepositions (place, time, direction, and dependent prepositions)',
      theory:
        'Для місця: in — усередині простору (in the room, in London), on — на поверхні (on the table, on the wall), at — у конкретній точці (at the door, at the bus stop). Для часу: in — місяці/роки/періоди доби (in July, in 2024, in the morning), on — дні й дати (on Monday, on 5th May), at — конкретний момент (at 6 o\'clock, at night, at the weekend у британській англійській). Багато дієслів і прикметників вимагають конкретного, "залежного" прийменника, який не завжди збігається з українським еквівалентом: interested IN (не "for"), good AT (не "in"), depend ON, afraid OF, married TO, responsible FOR — ці комбінації просто треба запам\'ятовувати як стійкі пари.',
      examples: [
        { en: 'The meeting is at 3 p.m. on Friday in March.', uk: 'Зустріч о 15:00 у п\'ятницю в березні (at для часу, on для дня, in для місяця).' },
        { en: "I'm really interested in learning Spanish.", uk: 'Мені справді цікаво вивчати іспанську (interested in, не for).' },
        { en: 'She is married to a doctor.', uk: 'Вона одружена з лікарем (married to, не with).' },
      ],
      exercises: [
        {
          id: 'prep-1',
          type: 'multiple-choice',
          prompt: 'I was born ___ 1998, ___ a small town.',
          options: ['in / in', 'on / at', 'at / on', 'in / at'],
          correctIndex: 0,
          explanation: 'In вживається і для років, і для великих просторів на кшталт міст/містечок.',
        },
        {
          id: 'prep-2',
          type: 'multiple-choice',
          prompt: "She's very good ___ maths, but bad ___ chemistry.",
          options: ['in / at', 'at / at', 'at / in', 'on / on'],
          correctIndex: 1,
          explanation: 'Good at і bad at — стійкі залежні прийменники.',
        },
        {
          id: 'prep-3',
          type: 'fill-blank',
          prompt: "Let's meet ___ the entrance ___ 7 o'clock.",
          correctAnswers: ['at, at'],
          explanation: 'At вживається і для конкретної точки місця, і для точного часу.',
        },
        {
          id: 'prep-4',
          type: 'fill-blank',
          prompt: "He's afraid ___ spiders.",
          correctAnswers: ['of'],
          explanation: 'Afraid of — стійка залежна пара прикметник+прийменник.',
        },
        {
          id: 'prep-5',
          type: 'multiple-choice',
          prompt: 'Which sentence uses the correct dependent preposition?',
          options: [
            'This decision depends of the budget.',
            'This decision depends on the budget.',
            'This decision depends in the budget.',
            'This decision depends to the budget.',
          ],
          correctIndex: 1,
          explanation: 'Depend on — фіксована залежна пара.',
        },
      ],
    },
  ],
}
