// Types
import type { GrammarCategory } from '@/types/grammarTopic'

export const tensesAspects: GrammarCategory = {
  id: 'tenses-aspects',
  language: 'en',
  title: 'Система часів і аспектів',
  description:
    'Чотири базові ситуації: проста дія (Simple), стан/предмет (to be), досвід чи результат (Perfect) і тривалість (Continuous) — у теперішньому, минулому та майбутньому.',
  topics: [
    {
      id: 'present-simple',
      title: 'Present Simple',
      theory:
        'Present Simple описує звички, факти, що завжди правдиві, розклади (потяги, кіно) і думки/почуття. Формула: I/you/we/they + V; he/she/it + V-s. Питання та заперечення — через do/does. Емфатичне do (I DO like it) підкреслює твердження, часто спростовуючи протилежне.',
      examples: [
        { target: 'She works as a teacher in Graz.', uk: 'Вона працює вчителькою в Граці.' },
        { target: 'Water boils at 100°C.', uk: 'Вода закипає при 100°C.' },
        { target: 'I do enjoy German grammar, actually.', uk: 'Мені й справді подобається німецька граматика.' },
      ],
      exercises: [
        {
          id: 'ps-1',
          type: 'multiple-choice',
          prompt: 'She ___ football every Sunday.',
          options: ['play', 'plays', 'playing', 'played'],
          correctIndex: 1,
          explanation: "З he/she/it у Present Simple додається -s: she plays.",
        },
        {
          id: 'ps-2',
          type: 'multiple-choice',
          prompt: '___ you speak German?',
          options: ['Do', 'Does', 'Are', 'Is'],
          correctIndex: 0,
          explanation: 'Питання з you утворюється допоміжним do: Do you speak...?',
        },
        {
          id: 'ps-3',
          type: 'fill-blank',
          prompt: 'The train ___ (leave) at 9 a.m. every day.',
          correctAnswers: ['leaves'],
          explanation: 'Розклади передаються Present Simple: he/she/it + -s → leaves.',
        },
        {
          id: 'ps-4',
          type: 'multiple-choice',
          prompt: 'He ___ like coffee, he prefers tea.',
          options: ["don't", "doesn't", 'not', 'isn\'t'],
          correctIndex: 1,
          explanation: "Заперечення з he/she/it: doesn't + інфінітив.",
        },
        {
          id: 'ps-5',
          type: 'fill-blank',
          prompt: 'A: You never call me. B: I ___ call you, you never answer!',
          correctAnswers: ['do'],
          explanation: 'Емфатичне do підсилює твердження і заперечує протилежну думку.',
        },
      ],
    },
    {
      id: 'present-continuous',
      title: 'Present Continuous',
      theory:
        'Present Continuous (am/is/are + V-ing) описує дію, що відбувається прямо зараз, тимчасовий процес навколо теперішнього моменту (не обов\'язково цієї секунди) або заплановану домовленість на найближче майбутнє. Не використовується зі статичними дієсловами (know, love, believe) — див. State Verbs.',
      examples: [
        { target: "I'm learning English this evening.", uk: 'Я вчу англійську цього вечора.' },
        { target: "She's working on a new project this month.", uk: 'Цього місяця вона працює над новим проєктом.' },
        { target: "We're meeting Anna at 6 p.m. tomorrow.", uk: 'Ми зустрічаємось з Анною завтра о 18:00 (домовленість).' },
      ],
      exercises: [
        {
          id: 'pc-1',
          type: 'multiple-choice',
          prompt: 'Listen! Someone ___ at the door.',
          options: ['knocks', 'is knocking', 'knock', 'knocked'],
          correctIndex: 1,
          explanation: 'Дія відбувається просто зараз (Listen!) → Present Continuous.',
        },
        {
          id: 'pc-2',
          type: 'multiple-choice',
          prompt: 'I ___ this book at the moment — it takes me ages.',
          options: ['read', 'am reading', 'reads', 'have read'],
          correctIndex: 1,
          explanation: 'Тривалий процес навколо теперішнього моменту (at the moment).',
        },
        {
          id: 'pc-3',
          type: 'fill-blank',
          prompt: 'We ___ (have) dinner with my parents on Friday — it\'s already arranged.',
          correctAnswers: ['are having'],
          explanation: 'Домовленість на майбутнє передається Present Continuous.',
        },
        {
          id: 'pc-4',
          type: 'multiple-choice',
          prompt: 'Choose the correct sentence.',
          options: ['I am knowing the answer.', 'I know the answer.', 'I knowing the answer.', 'I am know the answer.'],
          correctIndex: 1,
          explanation: 'Know — статичне дієслово, не вживається в Continuous.',
        },
        {
          id: 'pc-5',
          type: 'fill-blank',
          prompt: 'Why ___ you ___ (wear) a coat? It\'s warm outside.',
          correctAnswers: ['are, wearing', 'are wearing'],
          explanation: 'Питання в Present Continuous: Why are you wearing...?',
        },
      ],
    },
    {
      id: 'present-perfect',
      title: 'Present Perfect',
      theory:
        'Present Perfect (have/has + V3) з\'єднує минуле з теперішнім: результат зараз важливіший за час дії. Використовується для досвіду (ever/never), нещодавніх подій (just), незавершеного періоду (this week, so far) та дій, що почались у минулому й тривають (already/yet). На відміну від Past Simple, тут не називають конкретний момент у минулому.',
      examples: [
        { target: "I've lost my keys — I can't find them anywhere.", uk: 'Я загубив ключі — ніде не можу їх знайти (результат зараз).' },
        { target: 'Have you ever been to Vienna?', uk: 'Ти коли-небудь був у Відні?' },
        { target: "She's already finished her homework.", uk: 'Вона вже закінчила домашнє завдання.' },
      ],
      exercises: [
        {
          id: 'pp-1',
          type: 'multiple-choice',
          prompt: 'I ___ never ___ sushi before.',
          options: ['have / eat', 'have / eaten', 'has / eaten', 'did / eat'],
          correctIndex: 1,
          explanation: 'Досвід: have + V3 → have eaten.',
        },
        {
          id: 'pp-2',
          type: 'multiple-choice',
          prompt: 'Choose the correct sentence.',
          options: ['I have seen him yesterday.', 'I saw him yesterday.', 'I have saw him yesterday.', 'I seen him yesterday.'],
          correctIndex: 1,
          explanation: "Yesterday — конкретний момент у минулому → Past Simple, не Present Perfect.",
        },
        {
          id: 'pp-3',
          type: 'fill-blank',
          prompt: 'She ___ (just / arrive) — her suitcase is still by the door.',
          correctAnswers: ['has just arrived'],
          explanation: 'Just сигналізує щойно завершену дію з результатом зараз.',
        },
        {
          id: 'pp-4',
          type: 'multiple-choice',
          prompt: 'How many books ___ you ___ this year so far?',
          options: ['did / read', 'have / read', 'do / read', 'have / readed'],
          correctIndex: 1,
          explanation: 'This year (незавершений період) + so far → Present Perfect.',
        },
        {
          id: 'pp-5',
          type: 'fill-blank',
          prompt: 'We ___ (not / finish) the report yet.',
          correctAnswers: ["haven't finished", 'have not finished'],
          explanation: 'Yet у заперечних реченнях типово вживається з Present Perfect.',
        },
      ],
    },
    {
      id: 'present-perfect-continuous',
      title: 'Present Perfect Continuous',
      theory:
        'Present Perfect Continuous (have/has been + V-ing) підкреслює тривалість дії, що почалась у минулому й або триває досі, або щойно закінчилась, залишивши видимий результат/наслідок. Часто з for/since/how long, на відміну від Present Perfect Simple, де важливий факт/результат, а не сам процес тривання.',
      examples: [
        { target: "I've been learning German for two years.", uk: 'Я вчу німецьку вже два роки (і продовжую).' },
        { target: "She's tired because she's been working all day.", uk: 'Вона втомлена, бо працювала весь день (наслідок зараз).' },
        { target: 'How long have you been waiting?', uk: 'Скільки ти вже чекаєш?' },
      ],
      exercises: [
        {
          id: 'ppc-1',
          type: 'multiple-choice',
          prompt: 'Your eyes are red — ___ you ___ (cry)?',
          options: ['have / cried', 'have / been crying', 'did / cry', 'are / crying'],
          correctIndex: 1,
          explanation: 'Наслідок зараз (red eyes) від тривалого процесу → have been crying.',
        },
        {
          id: 'ppc-2',
          type: 'multiple-choice',
          prompt: 'They ___ for three hours — they must be exhausted.',
          options: ['have walked', 'have been walking', 'walked', 'are walking'],
          correctIndex: 1,
          explanation: 'For three hours підкреслює тривалість процесу.',
        },
        {
          id: 'ppc-3',
          type: 'fill-blank',
          prompt: 'I ___ (wait) for him since 8 o\'clock — where is he?',
          correctAnswers: ['have been waiting'],
          explanation: 'Since + момент початку → тривалість до зараз.',
        },
        {
          id: 'ppc-4',
          type: 'multiple-choice',
          prompt: 'Choose the sentence that emphasises the result, not the duration.',
          options: [
            "I've been reading this book for a week.",
            "I've read three books this week.",
            "I've been writing this essay all morning.",
            "She's been cooking since noon.",
          ],
          correctIndex: 1,
          explanation: 'Present Perfect Simple (не Continuous) вживається, коли важливий результат/кількість, а не процес.',
        },
        {
          id: 'ppc-5',
          type: 'fill-blank',
          prompt: 'How long ___ you ___ (learn) English?',
          correctAnswers: ['have, been learning', 'have been learning'],
          explanation: 'How long + Present Perfect Continuous — запитуємо про тривалість.',
        },
      ],
    },
    {
      id: 'past-simple',
      title: 'Past Simple',
      theory:
        'Past Simple описує завершені дії в конкретний момент/період у минулому (yesterday, in 2020, last week). Правильні дієслова + -ed, неправильні — за списком форм. Питання/заперечення — через did/didn\'t + інфінітив без to.',
      examples: [
        { target: 'I visited Berlin last summer.', uk: 'Я відвідав Берлін минулого літа.' },
        { target: 'She didn\'t call me yesterday.', uk: 'Вона не подзвонила мені вчора.' },
        { target: 'When did you move to Graz?', uk: 'Коли ти переїхав до Граца?' },
      ],
      exercises: [
        {
          id: 'pas-1',
          type: 'multiple-choice',
          prompt: 'We ___ to the cinema last Friday.',
          options: ['go', 'goes', 'went', 'have gone'],
          correctIndex: 2,
          explanation: 'Last Friday — конкретний час у минулому → Past Simple (go → went).',
        },
        {
          id: 'pas-2',
          type: 'multiple-choice',
          prompt: '___ she finish the exercise on time?',
          options: ['Did', 'Does', 'Was', 'Has'],
          correctIndex: 0,
          explanation: 'Питання в Past Simple утворюється через did + інфінітив.',
        },
        {
          id: 'pas-3',
          type: 'fill-blank',
          prompt: 'They ___ (not / see) the sign, so they missed the turn.',
          correctAnswers: ["didn't see", 'did not see'],
          explanation: 'Заперечення: didn\'t + інфінітив без to.',
        },
        {
          id: 'pas-4',
          type: 'fill-blank',
          prompt: 'I ___ (buy) this jacket in 2019.',
          correctAnswers: ['bought'],
          explanation: 'Buy — неправильне дієслово: buy → bought.',
        },
        {
          id: 'pas-5',
          type: 'multiple-choice',
          prompt: 'Which sentence is correct?',
          options: ['She was born in Kyiv.', 'She has born in Kyiv.', 'She is born in Kyiv.', 'She born in Kyiv.'],
          correctIndex: 0,
          explanation: 'Дата/факт народження в минулому — Past Simple пасивної форми: was born.',
        },
      ],
    },
    {
      id: 'past-continuous',
      title: 'Past Continuous',
      theory:
        'Past Continuous (was/were + V-ing) описує процес, що тривав у певний момент минулого, або дві паралельні дії. Класична пара: довша дія в Past Continuous переривається коротшою дією в Past Simple (I was cooking when the phone rang).',
      examples: [
        { target: 'I was cooking dinner when you called.', uk: 'Я готував вечерю, коли ти подзвонив.' },
        { target: 'At 8 p.m. we were still driving home.', uk: 'О 20:00 ми ще їхали додому.' },
        { target: 'While she was studying, he was watching TV.', uk: 'Поки вона навчалась, він дивився телевізор (паралельні дії).' },
      ],
      exercises: [
        {
          id: 'pac-1',
          type: 'multiple-choice',
          prompt: 'I ___ a shower when the fire alarm went off.',
          options: ['took', 'was taking', 'take', 'have taken'],
          correctIndex: 1,
          explanation: 'Довша дія у процесі, перервана коротшою (went off) → Past Continuous.',
        },
        {
          id: 'pac-2',
          type: 'multiple-choice',
          prompt: 'While I ___ dinner, she ___ the table.',
          options: ['cooked / was setting', 'was cooking / was setting', 'was cooking / set', 'cooked / set'],
          correctIndex: 1,
          explanation: 'Дві паралельні тривалі дії — обидві в Past Continuous.',
        },
        {
          id: 'pac-3',
          type: 'fill-blank',
          prompt: 'What ___ you ___ (do) at 10 p.m. last night?',
          correctAnswers: ['were, doing', 'were doing'],
          explanation: 'Питання про процес у конкретний момент минулого.',
        },
        {
          id: 'pac-4',
          type: 'fill-blank',
          prompt: 'She ___ (read) a book when the lights suddenly went out.',
          correctAnswers: ['was reading'],
          explanation: 'Тривала дія, перервана раптовою подією (Past Simple: went out).',
        },
        {
          id: 'pac-5',
          type: 'multiple-choice',
          prompt: 'Choose the correct combination: "The sun ___ brightly when we ___ the house."',
          options: ['shone / left', 'was shining / left', 'was shining / were leaving', 'shone / were leaving'],
          correctIndex: 1,
          explanation: 'Фон-опис (was shining) + коротка дія на цьому фоні (left).',
        },
      ],
    },
    {
      id: 'past-perfect',
      title: 'Past Perfect',
      theory:
        'Past Perfect (had + V3) — "доминуле": дія, що відбулась раніше за іншу вказану дію в минулому. Показує чітку послідовність двох подій у минулому: спочатку had + V3, потім Past Simple.',
      examples: [
        { target: 'When I arrived, the train had already left.', uk: 'Коли я прийшов, потяг уже поїхав (раніша подія).' },
        { target: "She'd never seen snow before she moved to Austria.", uk: 'Вона ніколи не бачила снігу до переїзду в Австрію.' },
        { target: 'I realised I had forgotten my passport.', uk: 'Я зрозумів, що забув паспорт.' },
      ],
      exercises: [
        {
          id: 'ppf-1',
          type: 'multiple-choice',
          prompt: 'By the time we got to the airport, the plane ___.',
          options: ['left', 'had left', 'has left', 'was leaving'],
          correctIndex: 1,
          explanation: 'Дія (left) сталась раніше за іншу минулу дію (got) → Past Perfect.',
        },
        {
          id: 'ppf-2',
          type: 'multiple-choice',
          prompt: 'She told me she ___ that film already.',
          options: ['saw', 'had seen', 'has seen', 'sees'],
          correctIndex: 1,
          explanation: 'Дія, що передувала моменту told у минулому → Past Perfect у непрямій мові.',
        },
        {
          id: 'ppf-3',
          type: 'fill-blank',
          prompt: 'I couldn\'t open the door because I ___ (lose) my key.',
          correctAnswers: ['had lost'],
          explanation: 'Втрата ключа сталась раніше за спробу відкрити двері.',
        },
        {
          id: 'ppf-4',
          type: 'fill-blank',
          prompt: 'After she ___ (finish) her studies, she moved to Graz.',
          correctAnswers: ['had finished'],
          explanation: 'After + Past Perfect підкреслює завершеність першої дії перед другою.',
        },
        {
          id: 'ppf-5',
          type: 'multiple-choice',
          prompt: 'Which sentence correctly shows the earlier of two past events?',
          options: [
            'When I called her, she left already.',
            'When I called her, she had already left.',
            'When I called her, she has already left.',
            'When I called her, she was leaving already.',
          ],
          correctIndex: 1,
          explanation: 'Виїзд стався до дзвінка → had already left.',
        },
      ],
    },
    {
      id: 'past-perfect-continuous',
      title: 'Past Perfect Continuous',
      theory:
        'Past Perfect Continuous (had been + V-ing) підкреслює тривалість дії, що йшла аж до певної точки в минулому (або до неї впритул), часто пояснюючи причину чогось, що сталося потім. Аналог Present Perfect Continuous, але зсунутий у минуле.',
      examples: [
        { target: 'He was tired because he had been working all night.', uk: 'Він був втомлений, бо працював усю ніч (до цього моменту в минулому).' },
        { target: 'They had been waiting for an hour when the bus finally came.', uk: 'Вони чекали годину, коли нарешті приїхав автобус.' },
        { target: 'The ground was wet — it had been raining.', uk: 'Земля була мокра — до цього йшов дощ.' },
      ],
      exercises: [
        {
          id: 'ppcont-1',
          type: 'multiple-choice',
          prompt: 'Her eyes were red because she ___.',
          options: ['had cried', 'had been crying', 'cried', 'has been crying'],
          correctIndex: 1,
          explanation: 'Наслідок у минулому (red eyes) від тривалого процесу до того моменту.',
        },
        {
          id: 'ppcont-2',
          type: 'multiple-choice',
          prompt: 'We ___ for two hours before the doctor finally called us in.',
          options: ['waited', 'had waited', 'had been waiting', 'were waiting'],
          correctIndex: 2,
          explanation: 'Тривалість (for two hours) до точки в минулому → Past Perfect Continuous.',
        },
        {
          id: 'ppcont-3',
          type: 'fill-blank',
          prompt: 'He ___ (study) English for years before he finally moved to London.',
          correctAnswers: ['had been studying'],
          explanation: 'Тривалий процес, що передував переїзду.',
        },
        {
          id: 'ppcont-4',
          type: 'fill-blank',
          prompt: 'The road was blocked because workers ___ (repair) it since morning.',
          correctAnswers: ['had been repairing'],
          explanation: 'Тривалість дії до відомого моменту в минулому.',
        },
        {
          id: 'ppcont-5',
          type: 'multiple-choice',
          prompt: 'Which best explains a past result caused by a preceding process?',
          options: [
            'I was hungry because I skipped breakfast.',
            'I was hungry because I had been working out for an hour.',
            'I was hungry because I work out.',
            'I am hungry because I had been working out.',
          ],
          correctIndex: 1,
          explanation: 'Причина в минулому (had been working out) → наслідок у минулому (was hungry).',
        },
      ],
    },
    {
      id: 'future-simple',
      title: 'Future Simple (will)',
      theory:
        'Will + інфінітив вживається для спонтанних рішень у момент мовлення, обіцянок, передбачень без конкретних доказів та пропозицій допомоги. Відрізняється від going to, яке базується на вже наявному намірі чи видимих доказах.',
      examples: [
        { target: "I'll help you with that — give me the bag.", uk: 'Я тобі допоможу — дай сумку (спонтанне рішення).' },
        { target: 'I think it will rain tomorrow.', uk: 'Думаю, завтра піде дощ (передбачення без доказів).' },
        { target: "I promise I'll call you tonight.", uk: 'Обіцяю, що подзвоню тобі ввечері.' },
      ],
      exercises: [
        {
          id: 'fs-1',
          type: 'multiple-choice',
          prompt: 'A: The phone is ringing. B: I ___ answer it.',
          options: ["'m going to", "'ll", 'am', 'will be'],
          correctIndex: 1,
          explanation: 'Спонтанне рішення в момент мовлення → will.',
        },
        {
          id: 'fs-2',
          type: 'multiple-choice',
          prompt: 'Look at those clouds — it ___ rain! (visible evidence now)',
          options: ['will', "'s going to", 'is', 'would'],
          correctIndex: 1,
          explanation: "Видимий доказ зараз (clouds) → going to, а не will.",
        },
        {
          id: 'fs-3',
          type: 'fill-blank',
          prompt: 'I ___ (not / forget) your birthday, I promise.',
          correctAnswers: ["won't forget", 'will not forget'],
          explanation: 'Обіцянка → will/won\'t.',
        },
        {
          id: 'fs-4',
          type: 'fill-blank',
          prompt: 'Experts believe the economy ___ (improve) next year.',
          correctAnswers: ['will improve'],
          explanation: 'Передбачення на основі думки/переконання, без видимих доказів → will.',
        },
        {
          id: 'fs-5',
          type: 'multiple-choice',
          prompt: '"I already bought a ticket to Vienna for Friday." This shows a decision made:',
          options: ['spontaneously, with will', 'in advance, with going to', 'as an offer, with shall', 'as a habit, with used to'],
          correctIndex: 1,
          explanation: 'Вже наявний намір/план (a ticket bought) типово описують going to, не will.',
        },
      ],
    },
    {
      id: 'future-continuous',
      title: 'Future Continuous',
      theory:
        'Future Continuous (will be + V-ing) описує процес, що триватиме в певний момент майбутнього, або дію, що відбудеться за звичайним планом/розкладом (без відтінку рішення чи наміру — просто констатація факту).',
      examples: [
        { target: 'This time tomorrow, I\'ll be flying to Vienna.', uk: 'Завтра о цій порі я летітиму до Відня.' },
        { target: "Don't call at 9 — I'll be sleeping.", uk: 'Не дзвони о 9-ій — я спатиму.' },
        { target: 'I\'ll be seeing him at the meeting anyway, so I\'ll tell him then.', uk: 'Я так чи інакше побачу його на зустрічі, тож скажу тоді (нейтральний факт).' },
      ],
      exercises: [
        {
          id: 'fc-1',
          type: 'multiple-choice',
          prompt: 'At 6 p.m. tomorrow, we ___ dinner.',
          options: ['will have', 'will be having', 'have', 'had'],
          correctIndex: 1,
          explanation: 'Процес у конкретний момент майбутнього → Future Continuous.',
        },
        {
          id: 'fc-2',
          type: 'multiple-choice',
          prompt: 'Choose the sentence describing an ongoing action at a future point.',
          options: [
            'I will finish the report by Friday.',
            'This time next week, I will be lying on a beach.',
            'I will go to the gym tomorrow.',
            'I have finished the report.',
          ],
          correctIndex: 1,
          explanation: 'This time next week + процес → Future Continuous.',
        },
        {
          id: 'fc-3',
          type: 'fill-blank',
          prompt: 'She ___ (work) at 3 p.m., so don\'t disturb her.',
          correctAnswers: ['will be working'],
          explanation: 'Процес у визначений момент майбутнього.',
        },
        {
          id: 'fc-4',
          type: 'fill-blank',
          prompt: 'This time next month, we ___ (travel) through Italy.',
          correctAnswers: ['will be travelling', 'will be traveling'],
          explanation: 'Тривалий процес у майбутньому, окреслений часовою рамкою.',
        },
        {
          id: 'fc-5',
          type: 'multiple-choice',
          prompt: 'Which is the most natural, neutral way to ask about someone\'s plans?',
          options: [
            'Will you be using the car this evening?',
            'Will you use the car this evening?',
            'Are you using the car this evening always?',
            'Do you use the car this evening?',
          ],
          correctIndex: 0,
          explanation: 'Future Continuous у питаннях часто звучить ввічливіше й нейтральніше, ніж прямий will-запит.',
        },
      ],
    },
    {
      id: 'future-perfect-continuous',
      title: 'Future Perfect / Future Perfect Continuous',
      theory:
        'Future Perfect (will have + V3) показує, що дія завершиться до певного моменту в майбутньому (by next year). Future Perfect Continuous (will have been + V-ing) додає акцент на тривалість цієї дії до того моменту (for five years by then).',
      examples: [
        { target: 'By 2027, I will have finished my degree.', uk: 'До 2027 року я закінчу навчання.' },
        { target: 'By next June, we will have been living here for five years.', uk: 'До наступного червня ми проживатимемо тут уже п\'ять років.' },
        { target: 'She will have left by the time you arrive.', uk: 'Вона вже поїде до того, як ти приїдеш.' },
      ],
      exercises: [
        {
          id: 'fpc-1',
          type: 'multiple-choice',
          prompt: 'By this time next year, she ___ her studies.',
          options: ['will finish', 'will have finished', 'finishes', 'will be finishing'],
          correctIndex: 1,
          explanation: 'Дія завершиться до вказаного моменту в майбутньому → Future Perfect.',
        },
        {
          id: 'fpc-2',
          type: 'multiple-choice',
          prompt: 'By December, they ___ in this apartment for ten years.',
          options: ['will live', 'will have lived', 'will have been living', 'lived'],
          correctIndex: 2,
          explanation: 'Наголос на тривалості до моменту → Future Perfect Continuous.',
        },
        {
          id: 'fpc-3',
          type: 'fill-blank',
          prompt: 'By the time he retires, he ___ (work) here for 30 years.',
          correctAnswers: ['will have been working'],
          explanation: 'Тривалість аж до майбутнього моменту (retires).',
        },
        {
          id: 'fpc-4',
          type: 'fill-blank',
          prompt: 'I hope I ___ (save) enough money by next summer.',
          correctAnswers: ['will have saved'],
          explanation: 'Завершеність дії до визначеного моменту в майбутньому.',
        },
        {
          id: 'fpc-5',
          type: 'multiple-choice',
          prompt: 'Which sentence focuses on completion rather than duration?',
          options: [
            'By 6 p.m. I will have been cooking for three hours.',
            'By 6 p.m. I will have finished cooking.',
            'By 6 p.m. I will be cooking.',
            'By 6 p.m. I am cooking.',
          ],
          correctIndex: 1,
          explanation: 'Future Perfect Simple акцентує факт завершення, не тривалість процесу.',
        },
      ],
    },
    {
      id: 'future-in-the-past',
      title: 'Future in the Past',
      theory:
        'Коли ми говоримо про майбутнє з точки зору минулого (наприклад, у непрямій мові чи розповіді), will замінюється на would, а be going to — на was/were going to. Це "майбутнє, яким воно бачилось тоді".',
      examples: [
        { target: 'He said he would call me back.', uk: 'Він сказав, що передзвонить мені.' },
        { target: 'She was going to study medicine, but she changed her mind.', uk: 'Вона збиралась вивчати медицину, але передумала.' },
        { target: 'I knew we would be late.', uk: 'Я знав, що ми запізнимось.' },
      ],
      exercises: [
        {
          id: 'fitp-1',
          type: 'multiple-choice',
          prompt: 'She told me she ___ (will) finish the project by Friday.',
          options: ['will', 'would', 'was', 'is going to'],
          correctIndex: 1,
          explanation: 'У непрямій мові про минуле will → would.',
        },
        {
          id: 'fitp-2',
          type: 'multiple-choice',
          prompt: 'He ___ study abroad, but he couldn\'t afford it.',
          options: ['will', 'would', 'was going to', 'is going to'],
          correctIndex: 2,
          explanation: 'Намір, що існував у минулому, але не здійснився → was going to.',
        },
        {
          id: 'fitp-3',
          type: 'fill-blank',
          prompt: 'I promised her I ___ (help) with the move.',
          correctAnswers: ['would help'],
          explanation: 'Обіцянка про майбутнє, передана з точки зору минулого → would.',
        },
        {
          id: 'fitp-4',
          type: 'fill-blank',
          prompt: 'We ___ (go) to the beach that day, but it started raining.',
          correctAnswers: ['were going to'],
          explanation: 'Запланована, але нездійснена дія в минулому.',
        },
        {
          id: 'fitp-5',
          type: 'multiple-choice',
          prompt: 'Which sentence correctly reports a past prediction?',
          options: [
            'He said the weather will be nice.',
            'He said the weather would be nice.',
            'He said the weather is nice.',
            'He said the weather has been nice.',
          ],
          correctIndex: 1,
          explanation: 'Пряме will у непрямій мові про минуле стає would.',
        },
      ],
    },
    {
      id: 'state-verbs',
      title: 'Статичні дієслова (State Verbs)',
      theory:
        'Дієслова стану (know, believe, love, hate, own, understand, seem, need, want) описують почуття, думки, володіння чи сприйняття, а не дію — тому вони зазвичай не вживаються в Continuous-формах. Деякі дієслова мають два значення: динамічне (можна в Continuous) і статичне (тільки Simple) — наприклад think (think that = вважати, статичне; be thinking = обдумувати, динамічне) чи have (have a car = володіти, статичне; be having lunch = їсти, динамічне).',
      examples: [
        { target: 'I know the answer.', uk: 'Я знаю відповідь (стан, не *I am knowing).' },
        { target: 'I think she is right.', uk: 'Я вважаю, що вона права (думка, статичне think).' },
        { target: "I'm thinking about changing jobs.", uk: 'Я обдумую зміну роботи (процес, динамічне think).' },
      ],
      exercises: [
        {
          id: 'sv-1',
          type: 'multiple-choice',
          prompt: 'Choose the correct sentence.',
          options: ['I am understanding the rule now.', 'I understand the rule now.', 'I understanding the rule now.', 'I do understanding the rule now.'],
          correctIndex: 1,
          explanation: 'Understand — статичне дієслово, не вживається в Continuous.',
        },
        {
          id: 'sv-2',
          type: 'multiple-choice',
          prompt: 'This soup ___ delicious!',
          options: ['is tasting', 'tastes', 'taste', 'is taste'],
          correctIndex: 1,
          explanation: 'Taste у значенні "мати смак" — статичне, Simple, не Continuous.',
        },
        {
          id: 'sv-3',
          type: 'fill-blank',
          prompt: 'I ___ (have) a red car — I bought it last year.',
          correctAnswers: ['have'],
          explanation: 'Have у значенні "володіти" — статичне, Present Simple.',
        },
        {
          id: 'sv-4',
          type: 'fill-blank',
          prompt: 'Right now, we ___ (have) lunch — can I call you back?',
          correctAnswers: ["'re having", 'are having'],
          explanation: 'Have у значенні "їсти" — динамічне, тому можливий Continuous.',
        },
        {
          id: 'sv-5',
          type: 'multiple-choice',
          prompt: 'Which verb below is normally NOT used in the continuous form?',
          options: ['run', 'cook', 'believe', 'write'],
          correctIndex: 2,
          explanation: 'Believe описує стан думки, а не дію — статичне дієслово.',
        },
      ],
    },
  ],
}
